[package]
name = "holochain_container"
version = "0.0.1"
authors = ["Holochain Core Dev Team <devcore@holochain.org>"]

[dependencies]
holochain_core_types = { path = "../core_types" }
holochain_container_api = { path = "../container_api" }
clap = "2"
