[package]
name = "holochain_locksmith"
version = "0.0.38-alpha7"
authors = ["Holochain Core Dev Team <devcore@holochain.org>"]
edition = "2018"
description = "helpers for mutex deadlock diagnosis"
keywords = ["holochain", "holo", "p2p"]
license = "GPL-3.0-only"
readme = "README.md"
documentation = "https://github.com/holochain/holochain-rust"
repository = "https://github.com/holochain/holochain-rust"

[dependencies]
backtrace = "=0.3.27"
chrono = "=0.4.6"
crossbeam-channel = "=0.3.8"
holochain_logging = "=0.0.4"
lazy_static = "=1.2.0"
log = "=0.4.8"
parking_lot ="=0.9.0"
snowflake = "=1.3.0"
