[package]
name = "hdk"
version = "0.0.1"
authors = ["Holochain Core Dev Team <devcore@holochain.org>"]

[dependencies]
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
bitflags = "1.0"
lazy_static = "1.1.0"
holochain_wasm_utils = { path = "../wasm_utils" }
holochain_dna = { path = "../dna" }
holochain_core_types = { path = "../core_types" }

[dev-dependencies]
test_utils = { path = "../test_utils" }
holochain_core_api = { path = "../core_api" }
holochain_core = { path = "../core" }
holochain_dna = { path = "../dna" }
tempfile = "3"
