[package]
name = "holochain_conductor_wasm"
version = "0.0.37-alpha12"
description = "holochain wasm"
license = "GPL-3.0-only"
homepage = "https://github.com/holochain/holochain-rust"
documentation = "https://github.com/holochain/holochain-rust"
authors = ["neonphog <neonphog@gmail.com>"]
edition = "2018"

[lib]
name = "holochain_conductor_wasm"
crate-type = ["cdylib"]

[dependencies]
holochain_core_types = { version = "=0.0.37-alpha12", path = "../core_types" }
wasm-bindgen = "=0.2.32"
