[package]
name = "holochain_conductor_wasm"
version = "0.0.32-alpha2"
authors = ["neonphog <neonphog@gmail.com>"]
edition = "2018"

[lib]
name = "holochain_conductor_wasm"
crate-type = ["cdylib"]

[dependencies]
holochain_core_types = {version = "=0.0.32-alpha2" , path = "../core_types" }
wasm-bindgen = "=0.2.32"
