[package]
name = "test-proc-macro"
version = "0.0.38-alpha5"
authors = ["Holochain Core Dev Team <devcore@holochain.org>"]

[lib]
crate-type = ["cdylib"]

[profile.release]
panic = "abort"

[workspace]
members = []

[dependencies]
hdk-proc-macros = { path = ".." }
hdk = { path = "../../hdk" }

serde = "=1.0.89"
serde_derive = "=1.0.89"
serde_json = { version = "=1.0.39", features = ["preserve_order"] }
holochain_json_derive = "=0.0.17"
