# https://www.appveyor.com/docs/enterprise/running-builds-on-aws/

build_cloud: master
image: hc-test

shallow_clone: true
version: 1.0.{build}
build: false
max_jobs: 20

environment:
 global:
  APPVEYOR_BUILD_WORKER_CLOUD: master
  hc_target_prefix: C:\build\

 matrix:
  - test_p: holochain_dna_c_binding
    test_path: dna_c_binding\

  - test_p: holochain_core_types
    test_path: core_types\

  - test_p: holochain_wasm_utils
    test_path: wasm_utils\
    wasm_path: wasm-test\integration-test\

  - test_p: hdk
    test_path: hdk-rust\
    wasm_path: wasm-test\

  - test_p: holochain_conductor_api
    test_path: conductor_api\
    wasm_path: wasm-test\
    wasm_path_2: test-bridge-caller\

  # - test_p: holochain_cas_implementations
  #   test_path: cas_implementations\

  - test_p: holochain_net
    test_path: net\

test_script:

 - scripts\windows\do-ci-test.bat

 # @see https://ci.appveyor.com/project/thedavidmeister/holochain-rust/builds/23358358
 # - SET "test_p=holochain_sodium"
 # - SET "test_path=sodium\"
 # - SET "wasm_path="
 # - SET "wasm_path_2="
 # - scripts\windows\do-ci-test.bat

 # @see https://ci.appveyor.com/project/thedavidmeister/holochain-rust/builds/23358584
 # - SET "test_p=hc"
 # - SET "test_path=cli\"
 # - SET "wasm_path="
 # - SET "wasm_path_2="
 # - scripts\windows\do-ci-test.bat

 # @see https://ci.appveyor.com/project/thedavidmeister/holochain-rust/builds/23357334
 # - SET "test_p=holochain_core"
 # - SET "test_path=core\"
 # - SET "wasm_path=src\nucleus\actions\wasm-test"
 # - SET "wasm_path_2="
 # - scripts\windows\do-ci-test.bat
