[package]
name = "nucleus-actions-tests"
version = "0.0.37-alpha10"
authors = ["Holochain Core Dev Team <devcore@holochain.org>"]

[lib]
crate-type = ["cdylib"]

[profile.release]
panic = "abort"

[workspace]
members = []

[dependencies]
hdk = { path = "../../../../../hdk" }
holochain_json_derive = "=0.0.17"
serde = "=1.0.89"
serde_json = { version = "=1.0.39", features = ["preserve_order"] }
serde_derive = "=1.0.89"
boolinator = "=2.4.0"
