[package]
name = "nucleus-actions-tests"
version = "0.0.46-alpha1"
authors = ["Holochain Core Dev Team <devcore@holochain.org>"]

[lib]
crate-type = ["cdylib"]

[profile.release]
panic = "abort"

[workspace]
members = []

[dependencies]
hdk = { path = "../../../../../hdk" }
holochain_json_derive = "=0.0.23"
serde = "=1.0.104"
serde_json = { version = "=1.0.47", features = ["preserve_order"] }
serde_derive = "=1.0.104"
boolinator = "=2.4.0"
