[[agents]]
id = "test agent 1"
name = "Holo Tester 1"
public_address = "HoloTester1-----------------------------------------------------------------------AAACZp4xHB"
key_file = "holo_tester.key"

[[agents]]
id = "test agent 2"
name = "Holo Tester 2"
public_address = "HoloTester2-----------------------------------------------------------------------AAAGy4WW9e"
key_file = "holo_tester.key"

[[dnas]]
id = "app spec rust"
file = "example-config/app_spec.hcpkg"
hash = "Qm328wyq38924y"

[[instances]]
id = "app spec instance 1"
dna = "app spec rust"
agent = "test agent 1"
[instances.storage]
type = "file"
path = "example-config/tmp-storage"

[[instances]]
id = "app spec instance 2"
dna = "app spec rust"
agent = "test agent 2"
[instances.storage]
type = "file"
path = "example-config/tmp-storage"


[[interfaces]]
id = "websocket interface"
[interfaces.driver]
type = "websocket"
port = 3000
[[interfaces.instances]]
id = "app spec instance 1"
[[interfaces.instances]]
id = "app spec instance 2"

[logger]
type = "debug"
