[package]
name = "holochain-node"
version = "0.0.5-alpha"
authors = ["Holochain Core Dev Team <devcore@holochain.org>"]
license = "MIT"
build = "build.rs"
exclude = ["artifacts.json", "index.node"]

[lib]
name = "holochain_node"
crate-type = ["dylib"]

[build-dependencies]
neon-build = "0.2.0"

[dependencies]
neon = "0.2.0"
serde = "1.0"
serde_derive = "^1.0"
serde_json = "^1.0"
holochain_conductor_api = { path = "../../conductor_api" }
holochain_core = { path = "../../core" }
holochain_core_types = { path = "../../core_types" }
holochain_node_test_waiter = { path = "../../nodejs_waiter" }
neon-serde = "0.1.1"
rust_sodium-sys = "0.10.3"
