[package]
name = "converse"
version = "0.0.43-alpha3"
authors = ["Julian Laubstein <contact@julianlaubstein.de>"]
edition = "2018"

[dependencies]
hdk = { path = "../../../../crates/hdk" }
serde = "=1.0.100"
serde_json = "=1.0.47"
serde_derive = "=1.0.100"

[lib]
path = "src/lib.rs"
crate-type = ["cdylib"]
