[package]
name = "converse"
version = "0.1.0"
authors = ["Julian Laubstein <contact@julianlaubstein.de>"]
edition = "2018"

[dependencies]
serde = "=1.0.89"
serde_json = "=1.0.39"
serde_derive = "=1.0.89"
hdk = { path = "../../../../hdk-rust" }

[lib]
path = "src/lib.rs"
crate-type = ["cdylib"]
