[package]
name = "test-globals"
version = "0.1.0"
authors = [""]

[lib]
crate-type = ["cdylib"]

[profile.release]
panic = "abort"
lto = true
opt-level = 'z'

[workspace]
members = []

[dependencies]
holochain_wasm_utils = { git = "https://github.com/holochain/holochain-rust" , branch = "develop" }
hdk = { path = ".." }
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
boolinator = "2.4"
