[package]
name = "test-globals"
version = "0.0.2"
authors = ["Holochain Core Dev Team <devcore@holochain.org>"]

[lib]
crate-type = ["cdylib"]

[profile.release]
panic = "abort"
lto = true
opt-level = 'z'

[workspace]
members = []

[dependencies]
hdk = { path = ".." }
holochain_wasm_utils = { path = "../../wasm_utils" }
serde = "1.0"
serde_derive = "1.0"
serde_json = { version = "1.0", features = ["preserve_order"] }
boolinator = "2.4"
holochain_core_types_derive = { path = "../../core_types_derive" }
