[package]
name = "holochain_logging"
version = "0.0.1"
authors = ["Holochain Core Dev Team <devcore@holochain.org>"]
edition = "2018"
description = "A logger for Holochain"
keywords = ["holochain", "holo", "p2p", "logging"]
categories = ["logging"]
license = "Apache-2.0"
readme = "README.md"
documentation = "https://github.com/holochain/holochain-rust"
repository = "https://github.com/holochain/holochain-rust"

[dependencies]
log = { version = "=0.4.8", features = ["std", "serde"] }
chrono = "=0.4.6"
crossbeam-channel = "=0.3.8"
regex = "=1.1.2"
colored = "=1.7.0"
toml = "=0.5.0"
serde = "=1.0.89"
serde_derive = "=1.0.89"
