[package]
name = <<NAME>>
version = "0.1.0"
authors = <<AUTHORS>>
edition = <<EDITION>>

[dependencies]
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
hdk = { git = "https://github.com/holochain/holochain-rust", branch = <<BRANCH>> }
holochain_wasm_utils = { git = "https://github.com/holochain/holochain-rust", branch = <<BRANCH>> }
holochain_core_types_derive = { git = "https://github.com/holochain/holochain-rust", branch = <<BRANCH>> }

[lib]
path = "src/lib.rs"
crate-type = ["cdylib"]
