[package]
name = "blog"
version = "0.0.32-alpha2"
authors = ["Holochain Core Dev Team <devcore@holochain.org>"]

[dependencies]
serde = "=1.0.89"
serde_json = { version = "=1.0.39", features = ["preserve_order"] }
hdk = { path = "../../../../hdk" }
hdk-proc-macros = { path = "../../../../hdk_v2" }

holochain_json_derive = "=0.0.17"
serde_derive = "=1.0.89"
boolinator = "=2.4.0"

[lib]
path = "src/lib.rs"
crate-type = ["cdylib"]
