[package]
name = "blog"
version = "0.0.33-alpha6"
authors = ["Holochain Core Dev Team <devcore@holochain.org>"]

[dependencies]
serde = "=1.0.89"
serde_json = { version = "=1.0.39", features = ["preserve_order"] }
hdk = { path = "../../../../crates/hdk" }
holochain_json_derive = "=0.0.17"
serde_derive = "=1.0.89"
boolinator = "=2.4.0"
[lib]
path = "src/lib.rs"
crate-type = ["cdylib"]
