[package]
name = "code"
version = "0.0.3"
authors = ["Holochain Core Dev Team <devcore@holochain.org>"]

[dependencies]
serde = "1.0"
serde_json = "1.0"
hdk = { path = "../../../../hdk-rust" }
holochain_core_types_derive = { path = "../../../../core_types_derive" }
serde_derive = "1.0"
boolinator = "2.4"

[lib]
path = "src/lib.rs"
crate-type = ["cdylib"]
