[package]
name = "sim1h"
version = "0.0.41-alpha4"
authors = ["Holochain Core Dev Team <devcore@holochain.org>"]
edition = "2018"
description = "A simulation of lib3h"
keywords = ["holochain", "holo", "p2p", "network", "simulation"]
categories = ["network-programming"]
license = "GPL-3.0-only"
readme = "../../README.md"
documentation = "https://github.com/holochain/holochain-rust"
repository = "https://github.com/holochain/holochain-rust"

[dependencies]
rusoto_core = "0.40.0"
rusoto_dynamodb = "0.40.0"
dynomite = "0.5"
futures = "0.1.21"
lib3h_protocol = "=0.0.25"
detach = "=0.0.19"
holochain_tracing = "=0.0.6"
uuid = { version = "0.4", features = ["v4"] }
log = "0.4.8"
env_logger = "=0.6.1"
lazy_static = "1.2.0"
holochain_persistence_api = "=0.0.11"
holochain_json_api = "=0.0.17"
url = "=2.1.0"
crossbeam-channel = "=0.3.8"
holochain_core_types = { version = "=0.0.41-alpha4", path = "../core_types" }
parking_lot = "0.9.0"
snowflake = "1.3.0"
