[package]
name = <<NAME>>
version = "0.1.0"
authors = <<AUTHORS>>
edition = <<EDITION>>

[dependencies]
serde = "=1.0.104"
serde_json = { version = "=1.0.47", features = ["preserve_order"] }
serde_derive = "=1.0.104"
hdk = <<VERSION>>
holochain_wasm_utils = <<VERSION>>
holochain_json_derive = "=0.0.20"

[lib]
path = "src/lib.rs"
crate-type = ["cdylib"]
