[package]
name = "hdk_proc_macros"
version = "0.0.34-alpha1"
description = "holochain hdk v2 (with proc macros)"
license = "Apache-2.0"
homepage = "https://github.com/holochain/holochain-rust"
documentation = "https://github.com/holochain/holochain-rust"
authors = ["Holochain Core Dev Team <devcore@holochain.org>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
syn = { version = "=0.15.31", features = ["full", "extra-traits"]}
quote = "=0.6.11"
proc-macro2 = "=0.4.27"
hdk = { version = "=0.0.34-alpha1", path = "../hdk" }
