[package]
name = "hdk"
edition = "2018"
version = "0.0.39-alpha1"
description = "holochain hdk"
license = "GPL-3.0-only"
homepage = "https://github.com/holochain/holochain-rust"
documentation = "https://github.com/holochain/holochain-rust"
authors = ["Holochain Core Dev Team <devcore@holochain.org>"]

[dependencies]
serde = "=1.0.89"
serde_derive = "=1.0.89"
serde_json = { version = "=1.0.39", features = ["preserve_order"] }
bitflags = "=1.0.4"
lazy_static = "=1.2.0"
holochain_wasm_utils = { version = "=0.0.39-alpha1", path = "../wasm_utils" }
holochain_core_types = { version = "=0.0.39-alpha1", path = "../core_types" }
holochain_json_api = "=0.0.17"
holochain_json_derive = "=0.0.17"
holochain_persistence_api = "=0.0.11"
pretty_assertions = "=0.6.1"
env_logger = "=0.6.1"
url = "=2.1.0"

[dev-dependencies]
test_utils = { version = "=0.0.39-alpha1", path = "../../test_utils" }
holochain_conductor_lib = { version = "=0.0.39-alpha1", path = "../conductor_lib" }
holochain_core = { version = "=0.0.39-alpha1", path = "../core" }
holochain_core_types = { version = "=0.0.39-alpha1", path = "../core_types" }
tempfile = "=3.0.7"
boolinator = "=2.4.0"
