[package]
name = "benchmarks"
version = "0.0.30-alpha6"
authors = ["Holochain Core Dev Team <devcore@holochain.org>"]

[dependencies]
holochain_core_types = { path = "../core_types" }
bencher = "=0.1.5"
tempfile = "=3.0.7"



[[bench]]
name = "my_benchmark"
harness = false
