[package]
name = "simple"
version = "0.0.44-alpha1"
authors = ["Ashanti Mutinta <Ashantimutinta@gmail.com>"]
edition = "2018"

[dependencies]
hdk = { path = "../../../../crates/hdk" }
serde = "=1.0.104"
serde_json = { version = "=1.0.47", features = ["preserve_order"] }
serde_derive = "=1.0.104"

[lib]
path = "src/lib.rs"
crate-type = ["cdylib"]
