[package]
name = "simple"
version = "0.0.37-alpha2"
authors = ["Ashanti Mutinta <Ashantimutinta@gmail.com>"]
edition = "2018"

[dependencies]
hdk = { path = "../../../../crates/hdk" }
serde = "=1.0.89"
serde_json = { version = "=1.0.39", features = ["preserve_order"] }
serde_derive = "=1.0.89"

[lib]
path = "src/lib.rs"
crate-type = ["cdylib"]
